### PR TITLE
Added new languages

### PR DESCRIPTION
**Pull request by elidare**
Added new languages supported by Yandex.Translate engine (https://github.com/matecat/MateCat/issues/762)

Added:
Bashkir (ba)
Hill Mari (mhr)
Mari (mrj)
Sundanese (su)
Udmurt (udm)

Enabled:
Amharic (am)
Javanese (jv)
Kannada (kn)
Lao (lo)
Latin (la)
Luxembourgish (lb)
Marathi (mr)
Punjabi (pa)
Papiamentu (pap)
Scots Gaelic (gd)
Sinhala (si)
Tajik (tg)
Yiddish (yi)

### CODE REVIEW

**Comment by Ostico** [comment]
Tnx for your PR, i will merge soon.

**Comment by Ostico** [comment]
Hi @elidare ,

this patch will be available in the next production release.

**Comment by elidare** [comment]
Thanks a lot!
If I may ask, when is the next release expected?

**Comment by Ostico** [comment]
It should be released in the next 1 or maximum 2 weeks.

**Pull request merged**
