### PR TITLE
Hotfix propagation

### PR DESCRIPTION
**Pull request by FrancescoE**

### CODE REVIEW

**Comment by freegenie** [comment]
I wonder if sprintf is as safe as PDO params. This solution doesn't look correct to me.

**Comment by Ostico** [comment]
Sure it is not the best solution but works for now. 
The right solution is to create ? placeholders as many id are in the array and call bindValue on the PDOStatement in a foreach statement.
It must be rewritten. Anyway, the list of IDs is get from a previous query, so it is safe enough.

**Comment by freegenie** [comment]
Got it. Anyway, I guess the bug is mine. Sorry guys!

**Comment by freegenie** [comment]
I turns out that I'm not able to reproduce this bug.

**Comment by Ostico** [comment]
To reproduce, you must have a document with more than one ID to propagate.
The PDOStatement transform the id imploded string in int and only the first id is evaluated.

Anyway, see this gist:
https://gist.github.com/Ostico/16afa402733ff3b6d15df9edf3ddad78

**Comment by freegenie** [comment]
Thanks now I got it. The problem with the tests I did is that it _seem_ to work properly in UI, because UI takes a different path from the server side process. The UI is updated in place, and also the word count show on page looks correct. This is only visible when you reload the page.

**Comment by freegenie** [comment]
BTW now that we have a list of propagated IDs, I think it would be better for the setTranslation to return the propagated IDs and have the UI update only those segments. This is likely to reduce and simplify client side code too.

**Comment by Ostico** [comment]
I'm working on it now

**Pull request merged**
